(define (problem vacuum)
  (:domain vacuum)
  (:objects entrance kitchen living_room corridor wc1 wc2 room1 room2 room3)

  (:init  (location entrance)
          (connected entrance kitchen)
          (connected entrance living_room)
          (connected entrance corridor)
          (connected kitchen entrance)
          (connected kitchen living_room)
          (connected living_room kitchen)
          (connected living_room entrance)
          (connected corridor wc1)
          (connected corridor wc2)
          (connected corridor room1)
          (connected corridor room2)
          (connected corridor room3)
          (connected corridor entrance)
          (connected wc2 corridor)
          (connected wc1 corridor)
          (connected room1 corridor)
          (connected room2 corridor)
          (connected room3 corridor)
          (recharge_room wc1)
        ;   (battery_100)
        ;   (battery_90)
        ;   (battery_80)
        ;   (battery_70)
        ;   (battery_60)
        ;   (battery_50)
        ;   (battery_40)
        ;   (battery_30)
          (battery_20)
          (battery_10)
          ;(clean corridor)
          )

  (:goal  (and (clean kitchen)
          (clean living_room)
          (clean entrance)
          (clean corridor)
          (clean wc1)
          (clean wc2)
          (clean room1)
          (clean room2)
          (clean room3)))        
)