;; domain file: domain-a1.pddl
(define (domain vacuum)
    (:requirements :strips :conditional-effects :negative-preconditions)
    (:predicates
        (location ?from)
        (connected ?from ?to)
        (clean ?room)
        (recharge_room ?room)
        (battery_100 ?battery )
        (battery_90 ?battery )
        (battery_80 ?battery )
        (battery_70 ?battery )
        (battery_60 ?battery )
        (battery_50 ?battery )
        (battery_40 ?battery )
        (battery_30 ?battery )
        (battery_20 ?battery )
        (battery_10 ?battery )
    )
    
        (:action Move
            :parameters (?from ?to ?battery)
            :precondition (and
                (location ?from)
                (connected ?from ?to)
                (battery_10 ?battery )
            )
            :effect (and
                (not (location ?from))
                (location ?to)
            )
        )
        
        (:action Recharge
            :parameters (?room ?battery)
            :precondition (and
                (location ?room)
                (recharge_room ?room)
                (battery_10 ?battery )
                )
            :effect (and
                (battery_100 ?battery)
                (battery_90 ?battery )
                (battery_80 ?battery )
                (battery_70 ?battery )
                (battery_60 ?battery )
                (battery_50 ?battery )
                (battery_40 ?battery )
                (battery_30 ?battery )
                (battery_20 ?battery )
                (battery_10 ?battery )))
        
        (:action Suck
            :parameters (?room ?battery)
            :precondition (and
                (location ?room)
                (battery_10 ?battery )
            )
            :effect (and
                (clean ?room)
                (when (and (battery_100 ?battery ))
                    (and (not (battery_100 ?battery ))
                ))
                (when (and (not (battery_100 ?battery )) (battery_90 ?battery ))
                    (and (not (battery_90 ?battery ))
                ))
                (when (and (not (battery_90 ?battery )) (battery_80 ?battery ))
                    (and (not (battery_80 ?battery ))
                ))
                (when (and (not (battery_80 ?battery )) (battery_70 ?battery ))
                    (and (not (battery_70 ?battery ))
                ))
                (when (and (not (battery_70 ?battery )) (battery_60 ?battery ))
                    (and (not (battery_60 ?battery ))
                ))
                (when (and (not (battery_60 ?battery )) (battery_50 ?battery ))
                    (and (not (battery_50 ?battery ))
                ))
                (when (and (not (battery_50 ?battery )) (battery_40 ?battery ))
                    (and (not (battery_40 ?battery ))
                ))
                (when (and (not (battery_40 ?battery )) (battery_30 ?battery ))
                    (and (not (battery_30 ?battery ))
                ))
                (when (and (not (battery_30 ?battery )) (battery_20 ?battery ))
                    (and (not (battery_20 ?battery ))
                ))
                (when (and (not (battery_20 ?battery )) (battery_10 ?battery ))
                    (and (not (battery_10 ?battery ))
                ))
                
            )
        )
)