(define (problem vacuum)
  (:domain vacuum)
  (:objects entrance kitchen living_room corridor wc1 wc2 room1 room2 room3 battery)

  (:init  (location entrance)
          (connected entrance kitchen)
          (connected entrance living_room)
          (connected entrance corridor)
          (connected kitchen entrance)
          (connected kitchen living_room)
          (connected living_room kitchen)
          (connected living_room entrance)
          (connected corridor wc1)
          (connected corridor wc2)
          (connected corridor room1)
          (connected corridor room2)
          (connected corridor room3)
          (connected corridor entrance)
          (connected wc2 corridor)
          (connected wc1 corridor)
          (connected room1 corridor)
          (connected room2 corridor)
          (connected room3 corridor)
          (recharge_room wc1)
          (battery_100 battery)
          (battery_90 battery)
          (battery_80 battery)
          (battery_70 battery)
          (battery_60 battery)
          (battery_50 battery)
          (battery_40 battery)
          (battery_30 battery)
          (battery_20 battery)
          (battery_10 battery)
          ;(clean corridor)
          )

  (:goal  (and (clean kitchen)
          (clean living_room)
          (clean entrance)
          (clean corridor)
          (clean wc1)
          (clean wc2)
          (clean room1)
          (clean room2)
          (clean room3)))        
)